
# 反向代理配置文件 - work-pc2
[[host]]
bind="https://192.168.0.116:5006/"
tlscert="./cert/work-pc2.crt"
tlskey="./cert/work-pc2.key"
target="http://192.168.0.116:5005/"
upstream="192.168.0.116:5005"
timeout=3000
